version: '3.8'

volumes:
  postgres-data: {}
  postgres-data-backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: wedo-app-postgres-data
    volumes:
      - postgres-data:/var/lib/postgresql/data:Z
      - postgres-data-backups:/backups:z
    env_file:
      - ./.env
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: wedo-backend
    volumes:
      - ./backend/:/usr/src/app/
    command: /usr/src/app/docker/django/start_dev
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: unless-stopped

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    depends_on:
      - django
    image: wedo-fronend
    volumes:
      - ./frontend/:/usr/src/app/
      - notused:/usr/src/app/node_modules/
    command: bash -c "rm -rf /usr/src/app/node_modules/* && pnpm run dev"
    ports:
      - '4200:4200'
