#!/bin/sh


python manage.py flush --no-input
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --no-input --clear
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/usr/src/app
